### ISSUE TITLE
Skill fails to start playing podcast

### ISSUE THREAD

**Issue by forslund** [the7erm/mycroft-skill-podcast#1]
When trying out the skill I have problem starting the **linux action show** podcast.

I get a `TypeError` in `subprocess.py` when trying to launch the application:

```
Traceback (most recent call last):
  File "/home/ake/projects/python/mycroft-core/mycroft/skills/core.py", line 208, in receive_handler
    handler(message)
  File "../mycroft-skill-podcast/__init__.py", line 277, in handle_listen_intent
    self.latest_show(message, True)
  File "../mycroft-skill-podcast/__init__.py", line 269, in latest_show
    subprocess.check_output(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

The problem seems to be that the link argument is not a string, instead it's a list of dicts:

``` python
[{'url': u'http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2016/linuxactionshowep435-432p.mp4', 'type': u'video/mp4', 'filesize': u'241831393'}]
```

To work around the problem I replaced line 267 of `__init__.py`:

`cmd = [open_cmd, link]`
 with
`cmd = [open_cmd, link[0]['url']]`.

This seems to work with all the podcasts in the example _feeds.json_ but I'm not sure how robust it is.

**Comment by the7erm** [comment]
I've added code to handle this situation and also limit the "play" process.

**Comment by the7erm** [comment]
https://github.com/the7erm/mycroft-skill-podcast/blob/master/__init__.py#L272
